// src/theme.js
export const lightTheme = {
  '--background-color': '#eee',
  '--background-color2': '#eee',
  '--text-color': '#495060',
  '--text-hover-color': '#2d8cf0',
  '--border-color': '#d3d3d3',
  '--announcement-title-color': '#495060',
  '--announcement-title-hover-color': '#2d8cf0',
  '--button-text-color': '#495060',
  '--search-box-color': 'fff',
  '--search-box-border-color': '#e0e1e4',
  '--search-box-hovor-color': '#2d8cf0',
  '--nav-backgound': '#fdfdfd',
  '--list-border-bottom': 'rgba(187, 187, 187, 0.5)',
  '--lecture-contest-detail': '',
  '--panelBackground': '#fff',
  '--panel-border-color': '#e9eaec',
  '--verticalMenu-item-backgound': '#fff',
  '--verticalMenu-item-color': '#495060',
  '--vertivalMenu-item-hover-color': 'f8f8f9',
  '--table-head-backgound': '#f8f8f9',
  '--table-body-background': '#fff',
  '--table-bottom-color': '#f8f8f9',
  '--table-border-color': '#e9eaec',
  '--table-text-color': '#495060',
  '--problem-text-color': '#3091f2',
  '--problem-example-box-color': '#e9eaec',
  '--qna-card-backgound': '#fff',
  '--qna-text-color': '#495060',
  '--qna-card-border-color': 'ebeef5'
  // 추가적인 스타일 정의
}
export const darkTheme = {
  '--background-color': '#222',
  '--background-color2': '#222',
  '--text-color': '#fff',
  '--text-hover-color': '#3498db',
  '--announcement-title-color': '#b4b4b4',
  '--announcement-title-hover-color': '#3498db',
  '--button-text-color': '#fff',
  '--search-box-color': '#2e2f2b',
  '--search-box-border-color': '#555',
  '--search-box-hovor-color': '#3498db',
  '--lecture-contest-detail': '2f2f2f',
  '--panelBackground': '#333',
  '--panel-border-color': '#222',
  '--nav-backgound': '#424242',
  '--border-color': '#222',
  '--list-border-bottom': 'rgba(255, 255, 255, 0.1)',
  '--verticalMenu-item-backgound': '#333',
  '--verticalMenu-item-color': '#b4b4b4',
  '--vertivalMenu-item-hover-color': '#444',
  '--table-head-backgound': '#444',
  '--table-body-background': '#2f2f2f',
  '--table-bottom-color': '#rgba(255, 255, 255, 0.1)',
  '--table-border-color': '#222',
  '--table-text-color': '#ececec',
  '--problem-text-color': '#3498db',
  '--problem-example-box-color': '#444',
  '--qna-card-backgound': '#444',
  '--qna-text-color': '#fff',
  '--qna-card-border-color': '222'
  // 추가적인 스타일 정의
}
